M48
; DRILL file {KiCad 8.0.1} date 2024-04-22T06:17:10+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-22T06:17:10+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X165.451Y-91.965
X165.451Y-95.965
T2
X150.281Y-92.009
X153.281Y-92.009
M30
