M48
; DRILL file {KiCad 8.0.1} date 2024-03-28T22:20:22+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-28T22:20:22+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X146.695Y-109.01
X150.695Y-109.01
T2
X136.364Y-106.685
X136.364Y-109.685
M30
