M48
; DRILL file {KiCad 8.0.1} date 2024-03-31T17:14:51+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-31T17:14:51+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X137.412Y-90.534
X141.412Y-90.534
T2
X146.842Y-92.007
X149.842Y-92.007
T3
X114.23Y-76.809
X114.23Y-84.809
M30
