M48
; DRILL file {KiCad 7.0.2} date Thu Jun  8 17:55:20 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-08T17:55:20+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X111.39Y-60.824
X115.39Y-60.824
T2
X94.87Y-64.746
X102.87Y-64.746
T0
M30
